name: Create release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      matrix:
        build:
          - 1
        include:
          - build: 1
            ubuntu-version: 18.04
            build-type: Release
            build-tests: 'ON'
            build-docs: 'OFF'
    name: 'Release ubuntu-${{ matrix.ubuntu-version }}
      <type=${{ matrix.build-type }},
       tests=${{ matrix.build-tests }},
       docs=${{ matrix.build-docs }}>'
    runs-on: ubuntu-${{ matrix.ubuntu-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set tag name
        id: set_tag_name
        run: echo ::set-output name=tag_name::${GITHUB_REF#refs/*/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ steps.set_tag_name.outputs.tag_name }}
          draft: false
          prerelease: false
